#!/bin/sh
bl_dev=/sys/class/backlight/intel_backlight

user=$(ps aux | grep xinit | head -1 | awk '{print $1}')

brightness=$(< $bl_dev/brightness)
maxbrightness=$(< $bl_dev/max_brightness)
step=$(bc <<< "scale=10;($brightness/($maxbrightness*2))^2*1000 + 1")
case $1 in
  -)
    newbrightness=$(bc <<< "($brightness - $step) / 1")
    if [[ $newbrightness -le 0 ]]; then
      newbrightness=1
    fi
    echo $newbrightness >$bl_dev/brightness &&
    runuser -l $user -c "notify-send 'Brightness: $(< $bl_dev/brightness)/$(< $bl_dev/max_brightness)' -h string:x-canonical-private-synchronous:1"
    ;;
  +)
    newbrightness=$(bc <<< "($brightness + $step) / 1")
    if [[ $newbrightness -gt $maxbrightness ]]; then
      newbrightness=$maxbrightness
    fi
    echo $newbrightness >$bl_dev/brightness &&
    runuser -l $user -c "notify-send 'Brightness: $(< $bl_dev/brightness)/$(< $bl_dev/max_brightness)' -h string:x-canonical-private-synchronous:1"
    ;;
esac
